### ISSUE TITLE
Token is not inserted in the request header after the login

### ISSUE THREAD

**Issue by WIBRC45920** [yalnguembu/vue-holiday#44]
- Fill the email
- Fill the password 
- Click on the login button
- You get the token and the user id
- But we aren't redirect to the user page
-

<img width="1440" alt="image" src="https://github.com/yalnguembu/vue-holiday/assets/73952440/d247f052-c060-4577-92ea-5285fa1bc474">

**Comment by WIBRC45920** [comment]
At the same time on mobile, the login is page is right displayed on the mobile. You can see in the screenshot above that the word `Login` is aligned with the text

For this version I think we need to have the logo of company (Just for this version in order to presented it first after presentation, remove it)

**Comment by yalnguembu** [comment]
Ok ithink for the logo it could be make quickly
